### ISSUE TITLE
Send plain text, not in attachments

### ISSUE THREAD

**Issue by hmiyado** [bitrise-steplib/steps-slack-message#29]
This integration is very helpful for me but I have one problem.
I would like to work together bitrise and bots in Slack.
However, this integration can have text only in attachments, so bots cannot respond to commands from bitrise.
Sending plain text, not in attachments makes very easy to do such cooperation.

**Comment by viktorbenei** [comment]
Hi @hmiyado ,

That's a great idea! If you have some time feel free to send us a PR! Alternatively use a Script step and `curl` to send the slack message any way you like!

We'll also discuss this with the team but unfortunately I believe this is a bit out of scope right now for our dev team (so many things to do!!).. But PRs are definitely welcome! ;)
