### ISSUE TITLE
first path segment in URL cannot contain colon: trim whitespace in URL

### ISSUE THREAD

**Issue by vdubedout** [bitrise-steplib/steps-slack-message#37]
Hi there, 
Trying to send builds do our slack but it fails with the error in the title. I have obfuscated a bit the urls but I can provide them if really needed. 

Thanks for any help

INFO[23:34:00] Start installing (golang) with apt-get       
INFO[23:34:00]  * [OK] Step dependency (go) installed, available. 
Config:
- Debug: false
- WebhookURL:  https://hooks.slack.com/services/xxxxxxxxxxxxx/xxxxxxxxx/xxxxxxxxxxxxxx 
- Channel: 
- ChannelOnError: #build-android
- Text: 
- TextOnError: 
- IconEmoji: 
- IconEmojiOnError: 
- IconURL: https://github.com/bitrise-io.png
- IconURLOnError: https://github.com/bitrise-io.png
- LinkNames: true
- Username: Bitrise
- UsernameOnError: Bitrise
- Color: #3bc3a3
- ColorOnError: #f0741f
- PreText: *Build Succeeded!*
- PreTextOnError: *Build Failed!*
- AuthorName: Vincent Dubedout
- Title: Merge branch 'freeze/2.1.0_store_deploy' into develop
- TitleOnError: 
- TitleLink: 
- Message: * freeze/2.1.0_store_deploy: when clicking enter, close keyboard
- MessageOnError: * freeze/2.1.0_store_deploy: when clicking enter, close keyboard
- ImageURL: 
- ImageURLOnError: 
- ThumbURL: 
- ThumbURLOnError: 
- Footer: Bitrise
- FooterIcon: https://github.com/bitrise-io.png?size=16
- TimeStamp: true
- Fields: App|xxxxxxxx
Branch|develop
Workflow|build_prod
- Buttons: View App|https://www.bitrise.io/app/xxxxxxxxxx
View Build|https://www.bitrise.io/build/xxxxxxxxxxxxx
Install Page|https://www.bitrise.io/artifact/xxxxxxxxxxxx
Error: failed to send the request: parse  https://hooks.slack.com/services/xxxxxxxxx/xxxxxxxxxx/xxxxxxxxxxxxxxxx : first path segment in URL cannot contain colon
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ! | slack@2.7.2 (exit code: 1)                                    | 3.47 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-slack-message/issues      |
| Source: https://github.com/bitrise-io/steps-slack-message                    |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Hi @vdubedout 

Can you please provide the related bitrise.io build's URL? This seems like a configuration issue, maybe there's an extra `:` or quotation somewhere, e.g. if you configured it in yml mode maybe you added an extra char.. Would have to check the build log/config to be able to tell you for sure

**Comment by vdubedout** [comment]
You can find it here
https://www.bitrise.io/build/45e68d04ccd7e603

**Comment by vdubedout** [comment]
it finally goes through. I think that the spaces before and after Url was the problem. Maybe doing a trim on the url text can avoid this kind of error

**Comment by viktorbenei** [comment]
Glad to hear it worked!

Marked this issue with `enhancement` - if you have some time feel free to send us a PR to do the whitespace trimming! We'll try to schedule this change, but it might take some time until we get to work on it.

**Comment by indera-shsp** [comment]
`strings.TrimSpace(url)` fixed it

**Comment by onmyway133** [comment]
I also have this problem, but for Generic File Storage, and it happens only on Pull request (feature branch -> master), not on push to master trigger

**Comment by viktorbenei** [comment]
@onmyway133 could you please contact our support via email or the onsite chat on bitrise.io ? We'll definitely need more info/context to reproduce the issue you reported.

**Comment by ofalvai** [comment]
Closing this issue, as it is already fixed by #66
