### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-slack-message#40]
- https://app.bitrise.io/build/60c59afb1ba28d0e

![image](https://user-images.githubusercontent.com/1173057/41946724-d50710ec-7981-11e8-9613-9af521c5b1de.png)
![image](https://user-images.githubusercontent.com/1173057/41946731-de832d22-7981-11e8-9f0a-5d3b8c0f314b.png)

Slack token is leaking on `version: 2.7.3` of the step.

😭

**Comment by godrei** [comment]
Hi @bootstraponline ,
to be honest, in this case your webhook url appears in the slack server's response. We need to print this response for debugging. In general we have no controll over every service and tool's messages and responses, so this kind of security issue can be solved by the secret filtering feature of the bitrise cli: https://github.com/bitrise-io/bitrise/blob/master/CHANGELOG.md#release-notes-2

**Comment by bootstraponline** [comment]
> We need to print this response for debugging. 

I think there's a better way though. On buddybuild the token is impossible to expose. The design is secure. It's even isolated from the build itself.

Bitrise is printing secrets by default for debugging. That's not good.

**Comment by godrei** [comment]
> I think there's a better way though.

Could you please share your toughts with us?

> It's even isolated from the build itself.

How could it be used during the build if it is isolated from the build?

Soon we will turn on secret filtering by default, other than that we will release a new version os sensitive steps, where the sensitive inputs will be marked and these inputs can hold only secret env vars, but no direct values.

**Comment by bootstraponline** [comment]
I have a meeting with bitrise tomorrow, we can chat about it more then. We're using a bunch of different CI systems and I see value in understanding how they solved the issue, even if it doesn't directly translate to bitrise.

**Comment by viktorbenei** [comment]
Definitely makes sense and thanks for reporting @bootstraponline !
Fix scheduled.

**Comment by viktorbenei** [comment]
**Details/reproduction:**

Issue happens if the Webhook URL is not a webhook URL, e.g. above it's just the value `secret-slack-token-123` instead of a URL e.g. `https://hooks.slack.com/services/X/Y/Z`

**Comment by BirmacherAkos** [comment]
Hi @bootstraponline ,

This issue has been fixed by the new CLI versions ( Bitrise CLI Secret filtering prevents this if the URL is set as a secret ).

I'm closing the issue, but if the issue persists for you even with the newest version of CLI please let us know.
