### ISSUE TITLE
Incorrectly reports API Token and Webhook URL are empty

### ISSUE THREAD

**Issue by maxlapides** [bitrise-steplib/steps-slack-message#54]
Yesterday, I realized that my Slack notifications weren't working anymore. Despite changing nothing, I started getting this error:

```Error: Both API Token and WebhookURL is empty. You need to provide one of them. If you want to use incoming webhooks provide the webhook url. I you want to use a bot to send a message provide the bot API token```

After a lot of debugging, I wasn't able to determine why the workflow step thought that the webhook URL was empty. I then switched the webhook URL with a bot token, and that worked once, so I thought I was set. Here's my new config:

```yml
    - slack:
        inputs:
        - api_token: "$SLACK_BOT_TOKEN"
```

Today, it stopped working again. I can't figure out what's wrong.

**Comment by fehersanyi-bitrise** [comment]
Hello there, Could you please send us your latest failing build's url so we could check out the logs for some more details? 🙃

**Comment by maxlapides** [comment]
@fehersanyi-bitrise sure, can you check these out?

https://app.bitrise.io/build/fedbedd4b24c7240
https://app.bitrise.io/build/57af03817bf279d6

**Comment by bitce** [comment]
Hey @maxlapides, it seems that both of these were PR builds, do you have this secret with the token enabled for PR builds?

**Comment by maxlapides** [comment]
Omg 🤦‍♂️that must be it. Thanks for the help!
