### ISSUE TITLE
Messages are not being sent

### ISSUE THREAD

**Issue by Jakester0813** [bitrise-steplib/steps-slack-message#57]
From the day that bitrise was setup with Slack, we were able to receive messages on Slack on the channel that was selected(even though the channel was private). Even yesterday the messages were being sent.

And then today when Bitrise made a build today, it failed to push to slack. This was the message that was recieved:

Error: server error: 404 Not Found, response: channel_not_found

Is there any reasons why this would happen?

**Comment by bitce** [comment]
Hi @Jakester0813! 

Sorry to hear about the issue. Can you please include a build URL?

Really depends on how you chose to set it up, but if you're using a webhook, those are created for channels. So if the channels or group messages. So if the channel was removed or the details have changed, that could result in this.

**Comment by Jakester0813** [comment]
We ended up using a public channel and that seems to fix the issue
