### ISSUE TITLE
Message not sent to multiple users

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [bitrise-steplib/steps-slack-message#59]
Hello folks,

I am trying to send a mensagem to more than one user, like this: 

![Screenshot 2019-07-09 at 17 53 57](https://user-images.githubusercontent.com/10619102/60904037-aa618500-a272-11e9-965a-9ad70d12cbc3.png)

I also tried without the pipe and with line breaks, no luck. Is this a bug or I just don't know how to use it?

**Comment by bitce** [comment]
@leandroBorgesFerreira  are you using a webhook by any chance? That has to be created for specific channels in mind and will only work for those. In case you are using a bot token, is it working for channels or not at all?

**Comment by leandroBorgesFerreira** [comment]
Yes, I am using webhooks. It works for channels as long as you don't have more than one. It also works for users as long as you don't have more than one. 

The problem I see is: It works for single users/channels, but it doesn't work for more than one. 

Sorry for the late response!

**Comment by bitce** [comment]
Could you send us examples of this happening? As this shouldn't be expected, according to the official Slack documentation [here](https://api.slack.com/incoming-webhooks), webhooks are created for specific channels and users and will only work for that channel or use it was created for.
