### ISSUE TITLE
Names not being linked?

### ISSUE THREAD

**Issue by gobetti** [bitrise-steplib/steps-slack-message#61]
Hi! Not sure if I'm using this incorrectly, but my Slack step includes for example `@gobetti` in the message field, the option "linkify names" has the default value (yes) and still, the messages being posted to Slack have a plain text rather than a link to my Slack user.

This happens to any of our users so it's not a problem specific with my Slack account.
This also happens in all of the positions I tried to place the tag (`message`, `text`, `author_name` and `title`).

I took a look at this feature's implementation and couldn't find anything that could justify this behavior, it looks like this linking is actually made by Slack and you're following [Slack's instructions to format messages](https://api.slack.com/docs/message-formatting), is that right? https://github.com/bitrise-steplib/steps-slack-message/pull/22

Let me know please if this is known to be an issue with Slack currently, or if I have it incorrectly configured. Thank you!

**Comment by bitce** [comment]
Hi @gobetti, thanks for the detailed report! 🙂

Can you please paste here a URL for a build which resulted in this behaviour?

**Comment by gobetti** [comment]
hi @bitce , thanks for answering! I ended up finding out today after some trial and error that it works however one needs to use the Slack's username (which is a private thing to each user). Interestingly if I try to tag someone in an actual Slack message, the username doesn't work. Closing this issue :)

**Comment by josinaldobarbosa** [comment]
To be recorded: https://api.slack.com/reference/surfaces/formatting#linking_to_channels_and_users

e.g.: My text <@ID_MEMBER_OR_CHANNEL_NOT_THE_NAME> blablabla
