### ISSUE TITLE
Feature Request: Option to skip aborted builds

### ISSUE THREAD

**Issue by dat-migdol** [bitrise-steplib/steps-slack-message#72]
My team would love to see an option to skip sending a message for aborted builds. As it stands, we often get put on alert when our `main` branch reports a build failed, only to look closer and see the build was actually aborted due to our rolling builds rule.

**Comment by bitce** [comment]
Hi @dat-migdol,

What does your workflow setup look like? Can you share an example build URL with us so we can see it? :) Is moving the step to the back end of the workflow, so in cases like this it gets aborted before it would run not an option?

**Comment by dat-migdol** [comment]
Thanks for getting back so quickly.

This step _is_ the last step in our workflows. Skipping this step altogether would skip aborts, but it would also skip general build failures which are still valuable for my team.

I'm considering adding a [run_if](https://devcenter.bitrise.io/steps-and-workflows/disable-a-step-by-condition/) expression to this slack step as a workaround, so long as I can sort out where the "Aborted" text in the below Slack message example originates.

__Example__
> ⛔️ Bitrise build #1234 failed @ def123 by @dat-migdol
Aborted - [project name]

**Comment by non-binary** [comment]
@dat-migdol The run_if expression is the solution in this case actually. Please let me know if you have any other questions.
