### ISSUE TITLE
Message still sending even though no channel name supplied

### ISSUE THREAD

**Issue by ColtonIdle** [bitrise-steplib/steps-slack-message#74]
It's sending messages on success to the channel declared in on failure. My use case is that I only want to see a slack message if the build fails and not on success. Using the latest version.

**Comment by Roland-Bak** [comment]
Hey there @ColtonIdle 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by ColtonIdle** [comment]
Still an issue. Easy to repro. Did it with a new project. /shrug

**Comment by cathyharmon** [comment]
Hello,

Sorry to hear you are still having this issue.  If you could send us the build URL and enable support access (under the "Settings" tab), we would be happy to take a look!

**Comment by ColtonIdle** [comment]
It's a private company repo. I unfortunately can't enable support access.

**Comment by ColtonIdle** [comment]
Still relevant. In the meantime, if anyone else hits this error, I just send to a specific private slack group that no one sees and the messages go there to die.

Would still be nice to not send the message at all if a receiving channel isn't defined.

**Comment by ColtonIdle** [comment]
Still persists.

**Comment by ofalvai** [comment]
Hello @ColtonIdle 👋 

> My use case is that I only want to see a slack message if the build fails and not on success.

The current behavior of this step is that it always sends a message either to `channel` or `channel_on_error`. I think what you want to achieve is not possible merely by configuring the step inputs. If you want to send a Slack message conditionally, you should [execute the entire step conditionally](https://devcenter.bitrise.io/en/steps-and-workflows/introduction-to-steps/enabling-or-disabling-a-step-conditionally.html#running-a-step-only-if-the-build-failed).

We'll add a note about this in the step description, thank you for raising this!

**Comment by ColtonIdle** [comment]
Thanks for the reply. That works for me.
