### ISSUE TITLE
Whitespace not trimmed on all inputs

### ISSUE THREAD

**Issue by DamienBitrise** [bitrise-steplib/steps-slack-message#75]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

https://github.com/bitrise-steplib/steps-slack-message/blob/master/main.go#L76

### Issue description

When there is leading or trailing whitespace in the input field for Channel it is not removed

### Steps to reproduce

1. Enter the channel name with a space before or after the channel name
2. Channel name is not trimmed for whitespace

**Comment by DiptoChakrabarty** [comment]
Hey can I fix this and send a PR , my plan is to use the strings package trimwhitespace function to remove the whitespaces on the c.Channel here https://github.com/bitrise-steplib/steps-slack-message/blob/d3ce902c2159b2d41aecd3b560092d1662b0970b/main.go#L77


Does this sound good?

**Comment by ofalvai** [comment]
Yup, this is a good idea! Looking forward to the PR.
